# @author OI
# @date August 5, 2013
# this code takes ssDNA and produces a complementary DNA string

def complement(ssDNA)
  comp_DNA = []
  ssDNA.split("").each do |base|
    case base
    when 'A'
      comp_DNA.unshift('T')
    when 'T'
      comp_DNA.unshift('A')
    when 'C'
      comp_DNA.unshift('G')
    when 'G'
      comp_DNA.unshift('C')
    end
  end
  
  comp_DNA.join("")
end

test = 'GTTTTTCCAAGCTATTAGGCGGTTAGCCAACCAGTATAGACTCATGTCGGACTGTACAAGGTGCCCTATAGGCTCCATCGTTGTCTACACATAGGGCATCTGCCCAGGAATAGTGAGTTCGGTGATGAGACGTAGCAGCCTCGGTGCAAATGCGTCCCACCGCCCGTCGATGCAGCCTGAAGCGCTACTGCCGCATCCTGGGACTCCTCTTGAGCTTAGATCTCAAGCTAATTGAGACCAACCCCCGACATTGGCTTTCAGGCCCCGTGGTGTTGGCAATAACGTAGCAGATGAGTAGTAAAGCACCCGAGCCCTGCAGACCCGGTGGCTCCACCACGGCCGGGTGGGCGGGTTGGCGCGATTTCTTACGGTTACGGCAAATCGAATGGGATTGGCAGAGGACGGGAGGGATCGAAAGCGGCCGCCTCACAATAGGTCTAGTCCCGACACAACCCCTCCTGGCCAGAGGGGGAGGTGACGTCTCGTGACTTCGGATTCATCTTGTAGCTAGCAAGTTACTGTTCCTTCGTATGCCCCGTATAAGCGAGCCAGCTTAGGCACGTATAAGCACGGGTATCGGTCATGTTTCGCTGCAAACGCCTGAGATGATAAAATATCTGTATCTTACACGCCTGGCGTGTATCACTCATATGCCGAAATCGGCGTGTGCCGTGTCCGGACGTGTTACGGTTTTGACTCCCAAATGTAAATCGAGCCTCTGCTAATGCAGGCTTGAGGAAGAGCAGGGGATACCGGGTCCATTGCTTTATTAAAACCGTAAATCTACCTGGAGGCCAAGTCGCTCCGTATCTTAGGCCCCAACCTCACCTAGTACCCGG'
puts (complement(test))