# @author OI
# @date August 5, 2013
# this code take a DNA sequence 's' and a substring 't' and finsds 
# all the index position in a sequence where substring occurs

def find(s, t)
  result = []
  n = t.length
  bases_array = s.split('')
  i = 0
  while i < t.length
    j = i
    while j < s.length
      result << (j + 1) if bases_array[j...(j + n)].join('') == t
      j += 1
    end
    i += 1
  end
  
  result.uniq.join(' ')
end

s = 'TTCCTGACTCCTGACCTCCTGACCAGTCCTGACTAAGAACGAACCTTCTGTTCCTGACATATATCATCCTGACAGTCCTGACAGTCCTGACCTCCTGACTCCTGACATCCTGACCTTCGATTCCTGACTAACCCGCAGTCCTGACTTCCTGACGTTCCTGACGTGCTCCTGACACCTCCTGACATCCTGACTTCCTGACATCCTGACAACTCCTGACCCCCTCATGATCCTGACGGATTCAGTGTTCCTGACTCCTGACTCTATCCTGACTCCTGACTTCCTGACCCACGTATCCTGACCGTCCTGACACAGTCCTGACGTCCTGACCCATCCTGACACGCTCCTGACTCCTGACTGGTATCCTGACCTCCTGACACGGTGTCCTGACAATTCCTGACCTGATCCTGACCTTCCTGACTTGCCAACCTACTCCTGACATATACGACATTTCCTGACGAGTCCTGACAGTCCTGACATCCGCGTCCTGACGCTGGTCCTGACTCCTGACTTTGTCCTGACATTTTGTCCTGACCTCATGTATACTCCTGACTCGCTCCTGACCAGGTCCTGACGGTCCTGACGTCCTGACTCCTGACTCCTGACGTTCCTGACTCCTGACACTCCTGACTAACAGCTCTGCGGGGCTCTTCCTGACTCCTGACGTCCTGACTCCTGACTCCTGACTCCTTCCTGACCTCCTGACTCGTCCTGACTCCTGACGTAATAGCCTAATCCTGACTCTGTGTTCCTGACGTCCTGACGCCGTCCTGACAGTCCTGACTTCCTGACGCACAGTCCTGACTGTAATCTCGATCCTGACGTCCTGACATATCCATCCTGACGCTCCTGACACCATCCTGACTGGTCTCCTGACCGCTCCTGACTCTCTCATGGTCCTGACCCTCCTGACTTCCTGACTCCTGACTCCTGACAAAGT'
t = 'TCCTGACTC'
puts find(s,t)